version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "Australia/Melbourne"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "Australia/Melbourne"
    groups:
      actions:
        patterns: ["*"]
