/**
 * fitzRoy-ts — TypeScript library for AFL data access.
 *
 * @packageDocumentation
 */

export {
  parseAflApiDate,
  parseAflTablesDate,
  parseFootyWireDate,
  toAestString,
} from "./lib/date-utils";
export { AflApiError, ScrapeError, ValidationError } from "./lib/errors";
export { type Err, err, type Ok, ok, type Result } from "./lib/result";
export { normaliseTeamName } from "./lib/team-mapping";
export {
  type AflApiToken,
  AflApiTokenSchema,
  type Competition,
  type CompetitionList,
  CompetitionListSchema,
  CompetitionSchema,
  type Compseason,
  type CompseasonList,
  CompseasonListSchema,
  CompseasonSchema,
  type MatchDetail,
  MatchDetailSchema,
  type MatchItem,
  type MatchItemList,
  MatchItemListSchema,
  MatchItemSchema,
  type MatchRoster,
  MatchRosterSchema,
  type MatchTeam,
  MatchTeamSchema,
  type PeriodScore,
  PeriodScoreSchema,
  type PlayerStatsItem,
  PlayerStatsItemSchema,
  type PlayerStatsList,
  PlayerStatsListSchema,
  type RosterPlayer,
  RosterPlayerSchema,
  type Round,
  type RoundList,
  RoundListSchema,
  RoundSchema,
  type SquadList,
  SquadListSchema,
  type SquadPlayerItem,
  SquadPlayerItemSchema,
  type TeamItem,
  TeamItemSchema,
  type TeamList,
  TeamListSchema,
  type TeamRoster,
  TeamRosterSchema,
} from "./lib/validation";
export type {
  CompetitionCode,
  DataSource,
  Fixture,
  Ladder,
  LadderEntry,
  LadderQuery,
  Lineup,
  LineupPlayer,
  LineupQuery,
  MatchQuery,
  MatchResult,
  MatchStatus,
  PlayerStats,
  PlayerStatsQuery,
  QuarterScore,
  RoundType,
  SeasonRoundQuery,
  Squad,
  SquadPlayer,
  SquadQuery,
  Team,
  TeamQuery,
} from "./types";
