/**
 * fitzRoy-ts — TypeScript library for AFL data access.
 *
 * @packageDocumentation
 */

export {
  parseAflApiDate,
  parseAflTablesDate,
  parseFootyWireDate,
  toAestString,
} from "./lib/date-utils";
export { AflApiError, ScrapeError, ValidationError } from "./lib/errors";
export { type Err, err, type Ok, ok, type Result } from "./lib/result";
export { normaliseTeamName } from "./lib/team-mapping";
export {
  type AflApiToken,
  AflApiTokenSchema,
  type CfsMatch,
  CfsMatchSchema,
  type CfsMatchTeam,
  CfsMatchTeamSchema,
  type CfsScore,
  CfsScoreSchema,
  type CfsVenue,
  CfsVenueSchema,
  type Competition,
  type CompetitionList,
  CompetitionListSchema,
  CompetitionSchema,
  type Compseason,
  type CompseasonList,
  CompseasonListSchema,
  CompseasonSchema,
  type MatchItem,
  type MatchItemList,
  MatchItemListSchema,
  MatchItemSchema,
  type MatchRoster,
  MatchRosterSchema,
  type PeriodScore,
  PeriodScoreSchema,
  type PlayerGameStats,
  PlayerGameStatsSchema,
  type PlayerStatsItem,
  PlayerStatsItemSchema,
  type PlayerStatsList,
  PlayerStatsListSchema,
  type RosterPlayer,
  RosterPlayerSchema,
  type Round,
  type RoundList,
  RoundListSchema,
  RoundSchema,
  type Score,
  ScoreSchema,
  type SquadList,
  SquadListSchema,
  SquadPlayerInnerSchema,
  type SquadPlayerItem,
  SquadPlayerItemSchema,
  SquadSchema,
  type TeamItem,
  TeamItemSchema,
  type TeamList,
  TeamListSchema,
  type TeamPlayers,
  TeamPlayersSchema,
  type TeamScore,
  TeamScoreSchema,
} from "./lib/validation";
export { AflApiClient, type AflApiClientOptions } from "./sources/afl-api";
export type {
  CompetitionCode,
  DataSource,
  Fixture,
  Ladder,
  LadderEntry,
  LadderQuery,
  Lineup,
  LineupPlayer,
  LineupQuery,
  MatchQuery,
  MatchResult,
  MatchStatus,
  PlayerStats,
  PlayerStatsQuery,
  QuarterScore,
  RoundType,
  SeasonRoundQuery,
  Squad,
  SquadPlayer,
  SquadQuery,
  Team,
  TeamQuery,
} from "./types";
